import type {Metadata} from "next";
import "../globals.css"
import Navbar from "@/components/ui/Navbar";
import Footer from "@/components/ui/Footer";
import LeftSideBar from "@/components/ui/LeftSideBar";
import RightSideBar from "@/components/ui/RightSideBar";
import {ClerkProvider} from "@clerk/nextjs";

export const metadata: Metadata = {
    title: "Clone thread",
    description: "Generated by Hesam Movahed",
};

export default function RootLayout({children}: { children: React.ReactNode }) {
    return (
        <ClerkProvider>
            <html>
            <body className={"bg-black"}>
            <Navbar/>
            <main className={"flex justify-between"}>
                <aside className={"hidden  md:block md:w-[10%] lg:w-[15%]  bg-gray-900 text-white p-1"}>
                    <LeftSideBar/>
                </aside>
                <section className={"w-full md:w-[90%] lg:w-[70%] h-screen bg-black"}>
                    <div className={"container mx-auto text-white"}>
                        {children}
                    </div>
                </section>
                <aside className={"hidden lg:block  bg-gray-900 lg:w-[15%] text-white p-1"}>
                    <RightSideBar/>
                </aside>
            </main>
            <Footer/>
            </body>
            </html>
        </ClerkProvider>
    );
}
